env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: mcli
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64

before:
  hooks:
    - go mod tidy

brews:
  - github:
      owner: dmirubtsov
      name: tap

    name: mcli
    homepage: "https://github.com/dmirubtsov/mcli"
    description: "A simple shortcut menu for shell commands"

nfpms:
  - id: mcli
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    vendor: Dmitry Rubtsov
    homepage: https://github.com/dmirubtsov/mcli

    maintainer: Dmitry Rubtsov <me@mazy.wtf>
    description: A simple shortcut menu for shell commands.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
