env:
  - CGO_ENABLED=0

builds:
  - binary: mcli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

brews:
  - tap:
      owner: dmirubtsov
      name: tap

    name: mcli
    homepage: "https://github.com/dmirubtsov/mcli"
    description: "A simple shortcut menu for shell commands"

nfpms:
  - id: mcli

    vendor: Dmitry Rubtsov
    homepage: https://github.com/dmirubtsov/mcli

    maintainer: Dmitry Rubtsov <me@mazy.wtf>
    description: A simple shortcut menu for shell commands.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
