env:
  - CGO_ENABLED=0

builds:
  - binary: mcli
    main: ./cmd/mcli
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

brews:
  - tap:
      owner: mazzz1y
      name: tap

    name: mcli
    homepage: "https://github.com/mazzz1y/mcli"
    description: "A simple shortcut menu for shell commands"

nfpms:
  - id: mcli

    vendor: Dmitry Rubtsov
    homepage: https://github.com/mazzz1y/mcli

    maintainer: mazzz1y <me@mazy.wtf>
    description: A simple shortcut menu for shell commands.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

aurs:
  - name: mcli-bin
    homepage: "https://github.com/mazzz1y/mcli"
    description: "Simple shortcut menu for shell commands."
    maintainers:
      - 'Dmitry Rubtsov <me@mazy.wtf>'
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/mcli-bin.git'
    provides:
      - mcli